FUNCTION "FC4_ZC_DISPONIBILIDAD_ENTIDAD" : Bool
TITLE = FC4_ZC_DISPONIBILIDAD_ENTIDAD
{ S7_Optimized_Access := 'TRUE' }
AUTHOR : ABH
FAMILY : ZeusControl
VERSION : 1.0
//Funcion para comprobar disponibilidad de las entidades.
   VAR_INPUT 
      Entidad : Int;   // Numero de entidad a gestionar
   END_VAR


BEGIN
	(*  
	ZEUS CONTROL, S.A.
	(c)Copyright (2023) All Rights Reserved
	--------------------------------------------------------------------------------------
	
	Software:       TIA Portal 16
	Restricciones:  PLC serie 1200/1500
	
	Nombre:         FC9_ZC_DISPONIBILIDAD_ENTIDAD
	Descripcion:    Funcion para comprobar disponibilidad de las entidades.
	
	Dependencias:
	    FC:         -
	    FB:         -
	    DB:         -
	    UDT:        ZC_ENTIDAD
	
	Change log:
	
	    Version     Fecha       Tecnico a cargo     Descripcion
	    
	    01.00.00    14.03.2025  (ABH)               Primera version.
	
	
	//=====================================================================================
	*)
	
	REGION GESTION_DISPONIBILIDAD    
	    
	    #FC4_ZC_DISPONIBILIDAD_ENTIDAD := "DB6_ENTIDAD".ENT[#Entidad].Estado.Disponible;
	    
	END_REGION
	
	
END_FUNCTION

